# Docker and Kolla-Ansible container services that must be enabled and
# running on the AIO node. One unit name per line, "#" for comments.
docker
kolla-cron-container.service
kolla-fluentd-container.service
kolla-glance_api-container.service
kolla-haproxy-container.service
kolla-heat_api-container.service
kolla-heat_api_cfn-container.service
kolla-heat_engine-container.service
kolla-horizon-container.service
kolla-keepalived-container.service
kolla-keystone-container.service
kolla-keystone_fernet-container.service
kolla-keystone_ssh-container.service
kolla-kolla_toolbox-container.service
kolla-mariadb-container.service
kolla-memcached-container.service
kolla-neutron_dhcp_agent-container.service
kolla-neutron_l3_agent-container.service
kolla-neutron_metadata_agent-container.service
kolla-neutron_openvswitch_agent-container.service
kolla-neutron_periodic_worker-container.service
kolla-neutron_rpc_server-container.service
kolla-neutron_server-container.service
kolla-nova_api-container.service
kolla-nova_compute-container.service
kolla-nova_conductor-container.service
kolla-nova_libvirt-container.service
kolla-nova_metadata-container.service
kolla-nova_novncproxy-container.service
kolla-nova_scheduler-container.service
kolla-nova_ssh-container.service
kolla-openvswitch_db-container.service
kolla-openvswitch_vswitchd-container.service
kolla-placement_api-container.service
kolla-proxysql-container.service
kolla-rabbitmq-container.service
kolla-skyline_apiserver-container.service
kolla-skyline_console-container.service
